#
#  Example requests to ModelProviderService in sidecar...
#
@sidecar = http://localhost:4005/-/cds/model-provider

### ------------------------------------------------------------------------
POST {{sidecar}}/getCsn
Content-Type: application/json

{}

### ------------------------------------------------------------------------
POST {{sidecar}}/getCsn
Content-Type: application/json

{ "for": "java", "toggles": ["*"] }

### ------------------------------------------------------------------------
POST {{sidecar}}/getEdmx
Content-Type: application/json

{ "service": "CatalogService", "for": "java", "flavor": "v2" }
