# Add integer extension field to Books
POST http://localhost:4004/extensibility/addExtension
Content-Type: application/json

{
  "extensions": [
    "{\"extend\":\"AdminService.Books\",\"elements\":{\"ab c\":{\"type\":\"cds.Integer\"}}}"
  ]
}

###
    # { "extend": "AdminService.Books", "elements":{
    #   "abc":{"type":"cds.Integer"}
    # }},
