@server = http://localhost:4005
@me = Authorization: Basic {{$processEnv USER}}:



POST {{server}}/-/cds/deployment/subscribe
Content-Type: application/json
Authorization: Basic xi:

{
  "tenant": "t1"
}
###

POST {{server}}/-/cds/deployment/subscribe
Content-Type: application/json
Authorization: Basic xi:

{
  "tenant": "t2"
}
###



PUT {{server}}/-/cds/saas-provisioning/t1
Content-Type: application/json
Authorization: Basic xi:

{
}
###