@media-store-service = http://localhost:4004/media
@browse-tracks-service = http://localhost:4004/browse-tracks

### ------------------------------------------------------------------------
# Get service 
GET {{media-store-service}}

### ------------------------------------------------------------------------
# Get $metadata document
GET {{media-store-service}}/$metadata

### ------------------------------------------------------------------------
# Get Artists
GET {{media-store-service}}/Artists

### ------------------------------------------------------------------------
# Get Albums
GET {{media-store-service}}/Albums
?$filter=artist_ID eq 1
&$expand=tracks,artist


### ------------------------------------------------------------------------
# Get Customers
GET {{media-store-service}}/Customers(1)
?$expand=supportRep

### ------------------------------------------------------------------------
# Get Employees
GET {{media-store-service}}/Employees(1)
?$expand=subordinates,reportsTo

### ------------------------------------------------------------------------
# Get Genres
GET {{media-store-service}}/Genres
?$top=10

### ------------------------------------------------------------------------
# Get InvoiceItems
GET {{media-store-service}}/InvoiceItems
?$expand=track,invoice&$top=10

### ------------------------------------------------------------------------
# Get Invoices
GET {{media-store-service}}/Invoices
?$top=10&$expand=customer

### ------------------------------------------------------------------------
# Get MediaTypes
GET {{media-store-service}}/MediaTypes
?$top=10

### ------------------------------------------------------------------------
# Get PlaylistTrack
GET {{media-store-service}}/PlaylistTrack/$count
?$filter=playlist_ID eq 8
# ?$count=true
# &$expand=track&$select=track

### ------------------------------------------------------------------------
# Get Playlists
GET {{media-store-service}}/Playlists
?$top=10

### ------------------------------------------------------------------------
# Get Playlists
GET {{media-store-service}}/Tracks
# ?$top=10&$expand=genre,mediaType,album


### ------------------------------------------------------------------------
# Get My tracks
POST {{browse-tracks-service}}/getInvoicedTracks
Content-Type: application/json
