# GraphQL
GET http://localhost:4007/graphql?query={BookshopService{Books{title,author{name},chapters{number,title}}}}

###

# OData
GET http://localhost:4007/bookshop/Books?$select=title&$expand=author($select=name),chapters($select=number,title)
