### Get remote suppliers

GET http://localhost:4004/notes/Suppliers?$top=11

### Get remote suppliers with expanded notes

GET http://localhost:4004/notes/Suppliers?$top=11&$expand=notes

### Suppliers set to readonly --> fails with 405

PATCH http://localhost:4004/notes/Suppliers('11')
Content-Type: application/json

{
    "BusinessPartnerFullName": "Can't change!"
}
