
@bookshop = http://localhost:4004
@reviews-service = {{bookshop}}/reviews
# Uncomment this when running a separate reviews service
@reviews-service = http://localhost:4005/reviews



#################################################
#
#   Reviews Service
#

GET {{reviews-service}}/Reviews

###

POST {{reviews-service}}/Reviews
Authorization: Basic {{$processEnv USER}}:
Content-Type: application/json

{"subject":"201", "title":"boo", "rating":3 }



#################################################
#
#   Bookshop Services
#

GET {{bookshop}}/browse/Books/201/reviews?
&$select=rating,date,title
&$top=3

###

GET {{bookshop}}/browse/Books(201)?
&$select=ID,title,rating
&$expand=reviews



#################################################
#
#   Orders Service
#

GET {{bookshop}}/orders/Orders
