@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:



POST {{server}}/-/cds/deployment/subscribe
Content-Type: application/json
Authorization: Basic xi:

{
  "tenant": "t1"
}
###

POST {{server}}/-/cds/deployment/subscribe
Content-Type: application/json
Authorization: Basic xi:

{
  "tenant": "t2"
}
###



PUT {{server}}/-/cds/saas-provisioning/tenant/t1
Content-Type: application/json
Authorization: Basic xi:

{
  "subscribedTenantId": "t1"
}
###


PUT {{server}}/-/cds/saas-provisioning/tenant/t2
Content-Type: application/json
Authorization: Basic xi:

{
  "subscribedTenantId": "t2"
}
###
