#################################################
#
#   To ReviewsService
#
# move the right down:
@reviews-service = http://localhost:4004/reviews
@reviews-service = http://localhost:5005/reviews

### Get all reviews
GET {{reviews-service}}/Reviews

### Add a new review (with random rating)
POST {{reviews-service}}/Reviews
Content-Type: application/json;IEEE754Compatible=true

{"subject":"201", "title":"boo"}



#################################################
#
#   Bookshop Requests involving reviews
#   (both in-process as well as separate one)
#

@bookshop = http://localhost:4004

### Request to CatalogService > delegated to ReviewsService
GET {{bookshop}}/browse/Books(201)/reviews?
&$select=rating,date,reviewer,title

### Alternative OData URL
GET {{bookshop}}/browse/Books/201/reviews?
&$select=rating,date,title
&$top=3

###
GET {{bookshop}}/browse/Books(201)?
&$select=ID,title,rating
&$expand=reviews
# Note: the $expand only works in case of ReviewsService in same process
